In [3]:
import torch

In [4]:
import torchvision

In [9]:
a = torch.tensor([[2,2,1],[4,5,6]])
print(a)

tensor([[2, 2, 1],
        [4, 5, 6]])


In [10]:
print(a.shape)
print(a.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [13]:
print(a.shape[0],a.shape[1])

2 3


In [14]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])

In [15]:
c = torch.tensor([2,2,1], dtype = torch.float)

In [16]:
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])

In [17]:
#Reshape b
#Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])


In [21]:
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim.round())
print(three_dim.view(2, 12).round())  # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1).round())



tensor([[[-1., -0.,  1.,  0.],
         [-1.,  1.,  1.,  1.],
         [-1.,  0.,  2., -1.]],

        [[-1.,  0.,  1., -0.],
         [ 1.,  0., -1., -1.],
         [ 0., -1.,  0.,  1.]]])
tensor([[-1., -0.,  1.,  0., -1.,  1.,  1.,  1., -1.,  0.,  2., -1.],
        [-1.,  0.,  1., -0.,  1.,  0., -1., -1.,  0., -1.,  0.,  1.]])
tensor([[-1., -0.,  1.,  0., -1.,  1.,  1.,  1., -1.,  0.,  2., -1.],
        [-1.,  0.,  1., -0.,  1.,  0., -1., -1.,  0., -1.,  0.,  1.]])


In [24]:
r = torch.rand(4,4)
print(r)

tensor([[0.1729, 0.3580, 0.8855, 0.5387],
        [0.1704, 0.9571, 0.6880, 0.3009],
        [0.4551, 0.0679, 0.1765, 0.1045],
        [0.0989, 0.5369, 0.5712, 0.2202]])


In [26]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [27]:
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

#Move the tensor to the GPU
r2 = r2.cuda()
print(r2)

tensor([[-0.1454, -1.0034,  0.7409,  1.2808],
        [ 0.5383,  0.0885, -1.1803, -0.2797],
        [ 1.7608, -1.6727, -0.3208,  0.0216],
        [ 0.2249,  0.9275, -0.8639, -1.7227]])
torch.float32


RuntimeError: cuda runtime error (30) : unknown error at ..\aten\src\THC\THCGeneral.cpp:74

In [28]:
#Provide Easy switching between CPU and GPU
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    add_result = add_result.cuda()
    print(add_result)

False


In [29]:
#You can also convert a list to a tensor
a = [2,3,4,1]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[2, 3, 4, 1]
tensor([2, 3, 4, 1]) torch.int64


In [31]:
#Tensor Concatenation 
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
#Concatenate along the 0 dimension (concatenate rows)
con_1 = torch.cat([first_1, second_1],0)
print('\n')
print(con_1)
print('\n')
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
# Concatenate along the 1 dimension (concatenate columns)
con_2 = torch.cat([first_2, second_2], 1)
print('\n')
print(con_2)
print('\n')

tensor([[ 1.4749, -0.0992,  0.2559,  0.4163,  0.8625],
        [-0.0740, -0.3441,  0.0237,  0.4128, -0.4807]])
tensor([[ 0.7257, -1.0996,  0.9211,  1.1918,  0.9330],
        [ 1.0694,  1.0862, -0.0717, -1.9877,  1.0121],
        [ 0.6396, -0.2935,  1.7021,  1.5975, -0.7414]])


tensor([[ 1.4749, -0.0992,  0.2559,  0.4163,  0.8625],
        [-0.0740, -0.3441,  0.0237,  0.4128, -0.4807],
        [ 0.7257, -1.0996,  0.9211,  1.1918,  0.9330],
        [ 1.0694,  1.0862, -0.0717, -1.9877,  1.0121],
        [ 0.6396, -0.2935,  1.7021,  1.5975, -0.7414]])


tensor([[-0.6709, -1.0505,  0.5973],
        [-0.1674, -1.0133,  1.7314]])
tensor([[ 0.5354, -0.5791,  1.7262,  0.0236,  0.4145],
        [-0.4081,  0.8494,  1.4980, -0.1216, -1.3631]])


tensor([[-0.6709, -1.0505,  0.5973,  0.5354, -0.5791,  1.7262,  0.0236,  0.4145],
        [-0.1674, -1.0133,  1.7314, -0.4081,  0.8494,  1.4980, -0.1216, -1.3631]])




In [34]:
#Adds a dimension of 1 along a specified index
tensor_1 = torch.tensor([1, 2, 3, 4])
print(tensor_1.shape)
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)

tensor_b = torch.unsqueeze(tensor_1,1)
print(tensor_b)
print(tensor_b.shape)
print('\n')

tensor_2 = torch.rand(2,3,4)
print(tensor_2)
print('\n')
tensor_c = tensor_2[:,:,2]
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c,2)
print(tensor_d)
print(tensor_d.shape)

torch.Size([4])
tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[[0.6561, 0.7074, 0.7983, 0.4529],
         [0.3775, 0.9105, 0.3349, 0.1615],
         [0.4886, 0.5808, 0.5535, 0.0999]],

        [[0.4217, 0.7812, 0.5267, 0.6731],
         [0.1528, 0.8140, 0.7739, 0.9010],
         [0.1075, 0.0743, 0.3369, 0.3360]]])


tensor([[0.7983, 0.3349, 0.5535],
        [0.5267, 0.7739, 0.3369]])
torch.Size([2, 3])


tensor([[[0.7983],
         [0.3349],
         [0.5535]],

        [[0.5267],
         [0.7739],
         [0.3369]]])
torch.Size([2, 3, 1])


In [35]:

#Remember, If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)
#Notice that both x and y have their required_grad set to true, therefore we an compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<ThAddBackward>)
tensor(21., grad_fn=<SumBackward0>)


In [36]:

#Now if we backpropagate on s, we can find the gradients of s with respect to x
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [37]:
# By default, Tensors have `requires_grad=False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)
#Another way to set the requires_grad = True is
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y

new_z = z.detach()
print(new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten. 
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history

#You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning 
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

False False
None
True
None
True
True
False
